Sprint 2
samgxlden/middle.messenger.praktikum.yandex pull request #2
Opened 2022-09-04 20:56 UTC by samgxlden

Теперь это SPA, вместо генерации статичных страниц
Подключен TypeScript
Добавлен компонентный подход
Проект структурирован
Добавлен класс для работы с запросами
Добавлены ESLint, Stylelint

Макет интерфейса в папке ui
Информация о проекте в файле README

2022-09-05 13:29 UTC, agadoev requested changes
Привет, спасибо за работу
Код структурированный, чистый, но есть над чем еще поработать
Из того, что точно нужно будет поправить:
1. Класс Validator реализован, но нигде не используется, нет привязки к onblur, onfocus (поправь, если ошибаюсь)
2. Сейчас падает npm run lint, с этим нужно разобраться

Из того, что я отметил в комментариях, поправь что сможешь, а если возникнут трудности - задавай вопрос в комментарии

Давай внесем правки и двинемся дальше :)

2022-09-05 13:29 UTC, agadoev commented on src/api/AuthAPI.ts
> +    }
```suggestion
    async signUp(data: SignUpData): Promise<unknown> {
        return await this.http.post("/signup", data);
    }
```

2022-09-05 13:29 UTC, agadoev commented on src/controllers/AuthController.ts
> +
У меня тут ts ругается. Это точно сработает?
<img width="924" alt="image" src="https://user-images.githubusercontent.com/37894659/188384602-3c4ed848-0323-47eb-8cf6-2cfc4bfd842d.png">

Но вообще я понял твою идею, она крутая. У нас в проекте используется похожая штука и мы для этого используем такой тип

```
type __ResourcePath<T, Key extends keyof T> = Key extends string
  ? T[Key] extends Record<string, unknown>
    ?
        | `${Key}.${__ResourcePath<T[Key], Exclude<keyof T[Key], keyof unknown[]>> &
            string}`
        | `${Key}.${Exclude<keyof T[Key], keyof unknown[]> & string}`
    : never
  : never

type _ResourcePath<T> = __ResourcePath<T, keyof T> | keyof T
```
тогда в методе store.set будет такая сигнатура
```
set(path: _ResourcePath<StoreData>, value: unknown);
```

2022-09-05 13:29 UTC, agadoev commented on src/components/RegisterMain/RegisterMain.template.hbs
> +<div>
Кажется тут нужно поправить отступы

2022-09-05 13:29 UTC, agadoev commented on src/controllers/AuthController.ts
> +        await this.fetchUser();
Вот этот вызов тоже неплохо бы обернуть в try catch

2022-09-05 13:29 UTC, agadoev commented on src/controllers/AuthController.ts
> +        const router = new Router();
Роутер используется в каждом методе класса AuthController. Чтобы не нарушать DRY его можно вынести в свойства класса и инициализировать в конструкторе

2022-09-05 13:29 UTC, agadoev commented on src/pages/login/index.ts
> +        console.log("Привет мир!");
console.log'и лучше в репозитории не держать, они отвлекают внимание и будут мешать твоим коллегам и тебе в будущем

2022-09-05 13:29 UTC, agadoev commented on src/utils/HTTPTransport.ts
> +    private request<Response>(
хорошее решение сделать этот метод приватным 👍 
но я бы еще пометил его как async, потому что он является асинхронным и возвращает промис

2022-09-05 13:29 UTC, agadoev commented on src/utils/Validator.ts
> +    email(value: string): [boolean, string] {
Интересное решение возвращать кортеж, но по хорошему такие функции-валидаторы должны возвращать только boolean. Объясню почему. Наверное ты знаешь про SOLID и первый принцип (SRP, принцип единственной ответственности) гласит о том, что модуль (функция, метод, класс и тд) должен иметь одну и только одну причину для изменения. Сейчас мы функцию можем изменить если
1) Изменится правило валидации (например регулярка)
2) Нужно будет изменить выводимый текст (или например вставить туда ссылку, у меня недавно такая задача как раз была в работе)

В общем я к тому, что это разные ответственности и по хорошему, принимать решение о том, какой текст должен выводиться на экран - это не ответственность валидатора, а ответственность компонента, который рендерит шаблон. Надеюсь ты понял :) Если что - задавай вопросы в комментах

2022-09-05 13:29 UTC, agadoev commented on src/utils/Validator.ts
> +                return !![value.length, "Значение не должно быть пустым"];
Тут есть тонкий момент, который можешь неплохо так улучшить код. Есть понятие - Exhaustive switch. Это очень полезная штука, которая подскажет нам, если мы забыли обработать какой-то кейс. Вообще основная задача TS - подсказывать нам пока мы пишем код. Попробуй сделать этот switch exhaustive. Вот [тут](https://stackoverflow.com/questions/39419170/how-do-i-check-that-a-switch-block-is-exhaustive-in-typescript) у человека такая же ситуация. 

В принципе я в этом коде проблемы не вижу, просто по опыту вижу, как можно улучшить. Если получится сделать - прекрасно, если нет - ничего страшного, код итак нормальный

2022-09-05 13:29 UTC, agadoev commented on tsconfig.json
> +    "noImplicitAny": true,
Я бы добавил сюда еще noImplicitReturns: true. Это правило заставляет нас прописывать явно все return'ы. Чем очевиднее и проще наш код - тем лучше :)

2022-09-09 12:00 UTC, samgxlden commented on tsconfig.json
> +    "noImplicitAny": true,
+

2022-09-09 12:02 UTC, samgxlden commented on src/api/AuthAPI.ts
> +    }
ESLint ругается

2022-09-09 12:11 UTC, samgxlden commented
Декомпозиция структуры
Валидация всех форм
Отдельные компоненты для кнопок и полей ввода
Настроен класс для работы с запросами
Настроены stylelint и ESLint

2022-09-09 15:06 UTC, agadoev approved these changes
Привет)
Спасибо за правки, я думаю, что код значительно улучшился. Работу принимаю, удачи в следующем спринте :)

2022-09-09 15:12 UTC, samgxlden commented
> Привет) Спасибо за правки, я думаю, что код значительно улучшился. Работу принимаю, удачи в следующем спринте :)

Спасибо!

2022-09-09 15:13 UTC, merged